version: "3.9"
services:
  web:
    build:
      context: .
    env_file: .env
    ports:
      - "${APP_PORT}:4000"
    depends_on:
      - db
    networks: ["default"]
    environment:
      - PORT=4000
      - NODE_ENV=development
      - DATABASE_URL=${DB_URL}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

  db:
    image: postgres:16
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    # Geçici: yerel build/test için host portu açıldı
    ports: ["5433:5432"]
    networks: ["default"]

volumes:
  db_data:
    name: "dewrk_db_data"

networks:
  default:
    name: "dewrk_net"
