// Auto-generated seed file
// Generated at: 2025-11-03T20:29:47.366Z
// Source: seed-output/testnets.json

import { PrismaClient, Difficulty, Status } from '@prisma/client';

const prisma = new PrismaClient();

const TESTNETS = [
  {
    "name": "Scroll - Native zkEVM Layer 2 for Ethereum",
    "slug": "scroll-native-zkevm-layer-2-for-ethereum",
    "network": "zkEVM",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "Native zkEVM Layer 2 for Ethereum",
    "logoUrl": "/logos/scroll-native-zkevm-layer-2-for-ethereum.png",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://scroll.io",
    "githubUrl": null,
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 83000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "Mantle Network | Building the Liquidity Chain of the Future",
    "slug": "mantle-network-or-building-the-liquidity-chain-of-the-future",
    "network": "Mantle Network | Building the Liquidity Chain of the Future",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "Mantle Network aims to be the \"Liquidity Chain\" to drive capital efficiency in the on-chain economy through modular architecture, data availability solutions, and zero-knowledge proofs.",
    "logoUrl": "/logos/mantle-network-or-building-the-liquidity-chain-of-the-future.jpg",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://mantle.xyz",
    "githubUrl": null,
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 3000000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "Fuel Ignition is Live!",
    "slug": "fuel-ignition-is-live",
    "network": "Fuel Ignition is Live!",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "Fuel Ignition is a high-performance Ethereum layer-2 rollup powered by the FuelVM; built for home verification and scalable for all.",
    "logoUrl": "/logos/fuel-ignition-is-live.png",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://fuel.network",
    "githubUrl": "https://github.com/FuelLabs",
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 80000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "ZKsync: The Elastic Network",
    "slug": "zksync-the-elastic-network",
    "network": "ZKsync: The Elastic Network",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "ZKsync helps banks and companies future-proof finance and expand into global digital assets with privacy and compliance.",
    "logoUrl": "/logos/zksync-the-elastic-network.png",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://zksync.io",
    "githubUrl": "https://github.com/matter-labs",
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 458000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "Linea: The L2 Where Ethereum Wins",
    "slug": "linea-the-l2-where-ethereum-wins",
    "network": "L2",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "Linea is the Layer 2 network built from first principles to strengthen Ethereum and the entire ETH economy.",
    "logoUrl": "/logos/linea-the-l2-where-ethereum-wins.png",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://linea.build",
    "githubUrl": null,
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 725000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "Homepage",
    "slug": "homepage",
    "network": "Homepage",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "Starknet uses STARK tech for computational integrity, validating off-chain transactions with advanced math and cryptography.",
    "logoUrl": "/logos/homepage.png",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://starknet.io",
    "githubUrl": null,
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 282000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "Optimism: The most used blockchain infrastructure.",
    "slug": "optimism-the-most-used-blockchain-infrastructure",
    "network": "Optimism: The most used blockchain infrastructure.",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "Own your infrastructure. Grow your margins. The most used blockchain infrastructure. Launch scalable, customizable Layer 2s and apps with Ethereum-grade security - powered by the OP Stack.",
    "logoUrl": "/logos/optimism-the-most-used-blockchain-infrastructure.jpg",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://optimism.io",
    "githubUrl": "https://github.com/ethereum-optimism",
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 178000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "Base",
    "slug": "base",
    "network": "Base",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "Base is an open stack that empowers builders, creators, and people everywhere to build apps, grow businesses, create what they love, and earn onchain.",
    "logoUrl": "/logos/base.png",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://base.org",
    "githubUrl": null,
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 100000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "Arbitrum — Build anything today",
    "slug": "arbitrum-build-anything-today",
    "network": "Arbitrum — Build anything today",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "Arbitrum: The ultimate Layer 2 scaling solution designed to enhance your Ethereum experience. Build faster, scale seamlessly, and unlock the full potential of the leading Layer 1 ecosystem.",
    "logoUrl": "/logos/arbitrum-build-anything-today.jpg",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://arbitrum.io",
    "githubUrl": null,
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 120000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "Sui | Deliver the Benefits of Web3 with the Ease of Web2",
    "slug": "sui-or-deliver-the-benefits-of-web3-with-the-ease-of-web2",
    "network": "Sui | Deliver the Benefits of Web3 with the Ease of Web2",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "Sui is a first-of-its-kind Layer 1 blockchain and smart contract platform designed to make digital asset ownership fast, private, secure, and accessible.",
    "logoUrl": "/logos/sui-or-deliver-the-benefits-of-web3-with-the-ease-of-web2.webp",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://sui.io",
    "githubUrl": "https://github.com/MystenLabs",
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 336000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "Aptos Developer Documentation",
    "slug": "aptos-developer-documentation",
    "network": "Aptos Developer Documentation",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "Aptos provides everything you need to build a best-in-class Web3 experience.",
    "logoUrl": "/logos/aptos-developer-documentation.png",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://aptos.dev",
    "githubUrl": "https://github.com/aptos-labs",
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 400000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "Global Financial Infrastructure for Everyone",
    "slug": "global-financial-infrastructure-for-everyone",
    "network": "Global Financial Infrastructure for Everyone",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "Solana is the high performance network powering internet capital markets, payments, and crypto applications. Fast. Decentralized. Scalable. Energy efficient. Solana can power thousands of transactions per second.",
    "logoUrl": "/logos/global-financial-infrastructure-for-everyone.jpg",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://solana.com",
    "githubUrl": null,
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 3350000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "Celestia - The Modular Blockchain Network | Celestia",
    "slug": "celestia-the-modular-blockchain-network-or-celestia",
    "network": "Celestia - The Modular Blockchain Network | Celestia",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "Celestia is the modular blockchain powering unstoppable applications with full-stack control. Deploy your own blockchain as easily as a smart contract with abundant throughput.",
    "logoUrl": "/logos/celestia-the-modular-blockchain-network-or-celestia.jpg",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://celestia.org",
    "githubUrl": "https://github.com/celestiaorg",
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 55000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "Celo: Ethereum Layer 2 for Payments, Stablecoins & DeFi",
    "slug": "celo-ethereum-layer-2-for-payments-stablecoins-and-defi",
    "network": "Layer 2",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "Celo is an Ethereum L2 powering fast, low-cost payments, native stablecoins, and DeFi apps — driving real-world adoption and financial inclusion worldwide.",
    "logoUrl": "/logos/celo-ethereum-layer-2-for-payments-stablecoins-and-defi.png",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://celo.org",
    "githubUrl": "https://github.com/celo-org",
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 56000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "Frax",
    "slug": "frax",
    "network": "Frax",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "The Financial Engine of the Internet",
    "logoUrl": "/logos/frax.png",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://frax.finance",
    "githubUrl": null,
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 525000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "Move your money fast",
    "slug": "move-your-money-fast",
    "network": "Move your money fast",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "Polygon is the fast, low-cost blockchain powering real-world assets and global payments, used by millions every day.",
    "logoUrl": "/logos/move-your-money-fast.png",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://polygon.technology",
    "githubUrl": "https://github.com/maticnetwork",
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 451000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "Blast",
    "slug": "blast",
    "network": "Blast",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "The Fullstack Chain",
    "logoUrl": "/logos/blast.png",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://blast.io",
    "githubUrl": null,
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 20000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "Mode Network",
    "slug": "mode-network",
    "network": "Mode Network",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "Scaling DeFi to billions of users through onchain agents and AI-powered financial applications. Mode is building the AI agents economy.",
    "logoUrl": "/logos/mode-network.png",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://mode.network",
    "githubUrl": null,
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 15000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "taiko.xyz",
    "slug": "taikoxyz",
    "network": "Unknown",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "",
    "logoUrl": null,
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://taiko.xyz",
    "githubUrl": null,
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 100000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "Zora",
    "slug": "zora",
    "network": "Zora",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "A social network where every post is a coin.",
    "logoUrl": "/logos/zora.jpg",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://zora.co",
    "githubUrl": null,
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 50000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "Ethereum Layer 2 Rollup platform - Metis",
    "slug": "ethereum-layer-2-rollup-platform-metis",
    "network": "Layer 2",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "Metis is a permissionless Ethereum Layer 2 network powering the next generation of decentralized applications.",
    "logoUrl": "/logos/ethereum-layer-2-rollup-platform-metis.jpg",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://metis.io",
    "githubUrl": "https://github.com/MetisProtocol",
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 100000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "Loopring - zkRollup Layer 2 for Trading and Payment",
    "slug": "loopring-zkrollup-layer-2-for-trading-and-payment",
    "network": "Rollup",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "Loopring is a zkRollup Layer 2 for Trading and Payment.",
    "logoUrl": "/logos/loopring-zkrollup-layer-2-for-trading-and-payment.jpg",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://loopring.org",
    "githubUrl": null,
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 45000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "dYdX: DeFi's Pro Trading Platform",
    "slug": "dydx-defis-pro-trading-platform",
    "network": "dYdX: DeFi's Pro Trading Platform",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "dYdX offers a decentralized trading platform designed for perpetual contracts, combining deep liquidity, advanced trading tools, and low fees. The mobile and web experience provides flexible trading options, including up to 50x buying power, with a focus on transparency and self-custody.",
    "logoUrl": "/logos/dydx-defis-pro-trading-platform.png",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://dydx.exchange",
    "githubUrl": "https://github.com/dydxprotocol",
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 87000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "Immutable | Powering the Next Generation of Games",
    "slug": "immutable-or-powering-the-next-generation-of-games",
    "network": "Immutable | Powering the Next Generation of Games",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "Immutable is the leading chain, wallet and growth suite for games.",
    "logoUrl": "/logos/immutable-or-powering-the-next-generation-of-games.jpg",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://immutable.com",
    "githubUrl": null,
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 500000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  },
  {
    "name": "World - The real human network.",
    "slug": "world-the-real-human-network",
    "network": "World - The real human network.",
    "status": "LIVE",
    "difficulty": "MEDIUM",
    "shortDescription": "Identity, finance and community for every human.",
    "logoUrl": "/logos/world-the-real-human-network.png",
    "rewardType": "Points",
    "rewardNote": "",
    "websiteUrl": "https://worldcoin.org",
    "githubUrl": null,
    "twitterUrl": null,
    "discordUrl": null,
    "dashboardUrl": null,
    "hasDashboard": false,
    "totalRaisedUSD": 250000000,
    "kycRequired": false,
    "requiresWallet": true,
    "tags": [],
    "highlights": [],
    "prerequisites": [],
    "gettingStarted": [],
    "discordRoles": []
  }
] as Array<{
  name: string;
  slug: string;
  network: string;
  status: Status;
  difficulty: Difficulty;
  rewardType: string;
  rewardNote?: string;
  shortDescription: string;
  logoUrl?: string;
  websiteUrl: string;
  githubUrl?: string;
  twitterUrl?: string;
  discordUrl?: string;
  dashboardUrl?: string;
  hasDashboard: boolean;
  totalRaisedUSD: number;
  kycRequired?: boolean;
  requiresWallet?: boolean;
  tags: string[];
  highlights: string[];
  prerequisites: string[];
  gettingStarted: string[];
  discordRoles?: Array<{ role: string; requirement: string; perk: string }>;
}>;

async function seedTestnets() {
  console.log('🌱 Seeding testnets...');
  await prisma.task.deleteMany();
  await prisma.testnet.deleteMany();
  
  await prisma.testnet.createMany({
    data: TESTNETS.map((testnet) => ({
      ...testnet,
      tags: testnet.tags,
      highlights: testnet.highlights,
      prerequisites: testnet.prerequisites,
      gettingStarted: testnet.gettingStarted,
      discordRoles: testnet.discordRoles ?? [],
    })),
  });
  
  console.log(`✅ ${TESTNETS.length} testnet seeded`);
}

async function main() {
  try {
    await seedTestnets();
  } catch (error) {
    console.error('❌ Seed failed', error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

// ESM'de require.main yok, direkt main çağır
main().catch((error) => {
  console.error('❌ Seed failed', error);
  process.exit(1);
});

export { seedTestnets, TESTNETS };
