export type AdminFormValues = {
  name: string;
  network: string;
  status: 'LIVE' | 'TBA' | 'ENDED' | 'UPCOMING';
  difficulty: 'EASY' | 'MEDIUM' | 'HARD';
  shortDescription: string;
  description: string;
  heroImageUrl: string;
  logoUrl: string;
  estTimeMinutes: string;
  rewardType: string;
  rewardNote: string;
  rewardCategory: string;
  rewardRangeUSD: string;
  totalRaisedUSD: string;
  hasFaucet: boolean;
  startDate: string;
  kycRequired: boolean;
  requiresWallet: boolean;
  hasDashboard: boolean;
  dashboardUrl: string;
  websiteUrl: string;
  githubUrl: string;
  twitterUrl: string;
  discordUrl: string;
  tags: string[];
  categories: string[];
  highlights: string[];
  prerequisites: string[];
  gettingStarted: Array<{ title: string; body: string; url: string }>;
  discordRoles: Array<{ role: string; requirement: string; perks: string }>;
  discordRolesJson?: string;
  tasks: Array<{ title: string; description: string; url: string; reward: string; order: number }>;
};
